#ifndef STATUS_H
#define STATUS_H

typedef enum {
    OK,
    NO_OPEN_BRACKET_AFTER_PRINT,
    NO_CLOSE_BRACKET_AFTER_VAR_IN_PRINT,
    UNEXPECTED_CHARACTERS_AFTER_PRINT,
    INVALID_VAR_IN_PRINT,
    UNKNOWN_VAR_IN_PRINT,
    EXPECTED_VAR_IN_ASSIGNMENT,
    NO_EQUAL_SIGN_IN_ASSIGNMENT,
    UNEXPECTED_CHARACTERS_AFTER_ASSIGNMENT,
    UNDEFINED_POWER_OPERATION,
    DIVISION_BY_ZERO,
    NO_CLOSE_BRACKET_AFTER_EXPRESSION,
    UNKNOWN_VAR_IN_EXPRESSION,
    UNEXPECTED_CHARACTER_IN_EXPRESSION
} Status;



void printStatus(Status status);
char *getStatusMsg(Status status);

#endif